import type { Metadata } from 'next';

import './globals.css';

import Navigation from './components/navigation/navigation';


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main className="min-h-screen pt-14 px-2.5 md:px-5">{children}</main>
      </body>
    </html>
  );
}
